### PR TITLE
About box. A proposal for #12

### PR DESCRIPTION
**Pull request by dimazest**

### CODE REVIEW

**Comment by dimazest** [comment]
It looks like this
screen shot 2016-03-25 at 14 22 45

**Comment by mr-c** [comment]
:+1:

**Comment by mr-c** [comment]
@dimazest Can I merge this?

**Comment by izaromanowska** [comment]
Looks good to me!

**Comment by dimazest** [comment]
Sure, merge it!

**Comment by dimazest** [comment]
I've updated http://mr-c.github.io/shouldacite/

**Pull request merged**
